#import "../../src/thesis/imports/preamble.typ": *
#import table: cell, header

#{
  table(
    columns: 7,
    align: (right,) + (center,) * 2,
    stroke: none,
    table.header(
      cell(rowspan: 2)[],
      table.vline(stroke: .5pt),
      cell(colspan: 3)[*Original*],
      table.vline(stroke: .5pt),
      cell(colspan: 3)[*Other*],
      [*researcher*],
      [*machine*],
      [*data*],
      [*researcher*],
      [*machine*],
      [*data*],
      table.hline(stroke: .5pt),
    ),
    [*Repeatability*],
    [\u{2713}],
    [\u{2713}],
    [\u{2713}],
    [],
    [],
    [],
    table.hline(stroke: .5pt + black.lighten(75%)),
    [*Runnability*],
    [\u{2713}],
    [],
    [\u{2713}],
    [],
    [\u{2713}],
    [],
    table.hline(stroke: .5pt + black.lighten(75%)),
    [*Reproducibility*],
    [],
    [],
    [\u{2713}],
    [\u{2713}],
    [\u{2713}],
    [],
    table.hline(stroke: .5pt + black.lighten(75%)),
    [*Replicability*],
    [],
    [],
    [],
    [\u{2713}],
    [\u{2713}],
    [\u{2713}],
  )
}
